"""pipedrive access token updated

Revision ID: 23109898456f
Revises: a1d06bfa72f3
Create Date: 2025-01-06 07:42:50.561295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23109898456f'
down_revision = 'a1d06bfa72f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pipedrive_tokens', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pipedrive_tokens', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###
