"""empty message

Revision ID: 38ae6183111e
Revises: 7a62ca578a4b
Create Date: 2025-01-07 08:57:53.307553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ae6183111e'
down_revision = '7a62ca578a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pipedrive_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('user_pipedrive_tokens_user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['creator_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pipedrive_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_pipedrive_tokens_user_email_key', ['user_email'])
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
