"""pipedrive creator_id added

Revision ID: 7a62ca578a4b
Revises: 23109898456f
Create Date: 2025-01-06 08:52:29.772885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a62ca578a4b'
down_revision = '23109898456f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pipedrive_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pipedrive_tokens', schema=None) as batch_op:
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
