"""domain added in leads

Revision ID: 97f08cba521e
Revises: 1c4a95a2ff84
Create Date: 2024-12-06 18:24:46.639273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f08cba521e'
down_revision = '1c4a95a2ff84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubspot_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adviser_name', sa.String(length=255), nullable=True),
    sa.Column('lead_name', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('lead_title', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hubspot_token')
    op.drop_table('lead')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('adviser_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lead_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lead_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lead_pkey')
    )
    op.create_table('hubspot_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hubspot_token_pkey')
    )
    op.drop_table('leads')
    op.drop_table('hubspot_tokens')
    # ### end Alembic commands ###
